// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.LambdaBuilders
{
    public static class BuildGo
    {
        public static Task<BuildGoResult> InvokeAsync(BuildGoArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<BuildGoResult>("lambda-builders:index:buildGo", args ?? new BuildGoArgs(), options.WithDefaults());

        public static Output<BuildGoResult> Invoke(BuildGoInvokeArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<BuildGoResult>("lambda-builders:index:buildGo", args ?? new BuildGoInvokeArgs(), options.WithDefaults());
    }


    public sealed class BuildGoArgs : global::Pulumi.InvokeArgs
    {
        [Input("architecture")]
        public string? Architecture { get; set; }

        [Input("code")]
        public string? Code { get; set; }

        public BuildGoArgs()
        {
        }
        public static new BuildGoArgs Empty => new BuildGoArgs();
    }

    public sealed class BuildGoInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("architecture")]
        public Input<string>? Architecture { get; set; }

        [Input("code")]
        public Input<string>? Code { get; set; }

        public BuildGoInvokeArgs()
        {
        }
        public static new BuildGoInvokeArgs Empty => new BuildGoInvokeArgs();
    }


    [OutputType]
    public sealed class BuildGoResult
    {
        public readonly Archive? Asset;

        [OutputConstructor]
        private BuildGoResult(Archive? asset)
        {
            Asset = asset;
        }
    }
}
