// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.lambdabuilders;

import com.pulumi.core.Output;
import com.pulumi.core.TypeShape;
import com.pulumi.deployment.Deployment;
import com.pulumi.deployment.InvokeOptions;
import com.pulumi.lambdabuilders.Utilities;
import com.pulumi.lambdabuilders.inputs.BuildGoArgs;
import com.pulumi.lambdabuilders.inputs.BuildGoPlainArgs;
import com.pulumi.lambdabuilders.outputs.BuildGoResult;
import java.util.concurrent.CompletableFuture;

public final class LambdabuildersFunctions {
    public static Output<BuildGoResult> buildGo() {
        return buildGo(BuildGoArgs.Empty, InvokeOptions.Empty);
    }
    public static CompletableFuture<BuildGoResult> buildGoPlain() {
        return buildGoPlain(BuildGoPlainArgs.Empty, InvokeOptions.Empty);
    }
    public static Output<BuildGoResult> buildGo(BuildGoArgs args) {
        return buildGo(args, InvokeOptions.Empty);
    }
    public static CompletableFuture<BuildGoResult> buildGoPlain(BuildGoPlainArgs args) {
        return buildGoPlain(args, InvokeOptions.Empty);
    }
    public static Output<BuildGoResult> buildGo(BuildGoArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("lambda-builders:index:buildGo", TypeShape.of(BuildGoResult.class), args, Utilities.withVersion(options));
    }
    public static CompletableFuture<BuildGoResult> buildGoPlain(BuildGoPlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("lambda-builders:index:buildGo", TypeShape.of(BuildGoResult.class), args, Utilities.withVersion(options));
    }
}
