// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.lambdabuilders.inputs;

import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class BuildGoPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final BuildGoPlainArgs Empty = new BuildGoPlainArgs();

    @Import(name="architecture")
    private @Nullable String architecture;

    public Optional<String> architecture() {
        return Optional.ofNullable(this.architecture);
    }

    @Import(name="code")
    private @Nullable String code;

    public Optional<String> code() {
        return Optional.ofNullable(this.code);
    }

    private BuildGoPlainArgs() {}

    private BuildGoPlainArgs(BuildGoPlainArgs $) {
        this.architecture = $.architecture;
        this.code = $.code;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(BuildGoPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private BuildGoPlainArgs $;

        public Builder() {
            $ = new BuildGoPlainArgs();
        }

        public Builder(BuildGoPlainArgs defaults) {
            $ = new BuildGoPlainArgs(Objects.requireNonNull(defaults));
        }

        public Builder architecture(@Nullable String architecture) {
            $.architecture = architecture;
            return this;
        }

        public Builder code(@Nullable String code) {
            $.code = code;
            return this;
        }

        public BuildGoPlainArgs build() {
            return $;
        }
    }

}
