// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.lambdabuilders.inputs;

import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class BuildGoPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final BuildGoPlainArgs Empty = new BuildGoPlainArgs();

    /**
     * Lambda function architecture to build for. Valid values are `&#34;x86_64&#34;` and `&#34;arm64&#34;`. Default is `&#34;x86_64&#34;`.
     * 
     */
    @Import(name="architecture")
    private @Nullable String architecture;

    /**
     * @return Lambda function architecture to build for. Valid values are `&#34;x86_64&#34;` and `&#34;arm64&#34;`. Default is `&#34;x86_64&#34;`.
     * 
     */
    public Optional<String> architecture() {
        return Optional.ofNullable(this.architecture);
    }

    /**
     * The path to the go code to build
     * 
     */
    @Import(name="code")
    private @Nullable String code;

    /**
     * @return The path to the go code to build
     * 
     */
    public Optional<String> code() {
        return Optional.ofNullable(this.code);
    }

    private BuildGoPlainArgs() {}

    private BuildGoPlainArgs(BuildGoPlainArgs $) {
        this.architecture = $.architecture;
        this.code = $.code;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(BuildGoPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private BuildGoPlainArgs $;

        public Builder() {
            $ = new BuildGoPlainArgs();
        }

        public Builder(BuildGoPlainArgs defaults) {
            $ = new BuildGoPlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param architecture Lambda function architecture to build for. Valid values are `&#34;x86_64&#34;` and `&#34;arm64&#34;`. Default is `&#34;x86_64&#34;`.
         * 
         * @return builder
         * 
         */
        public Builder architecture(@Nullable String architecture) {
            $.architecture = architecture;
            return this;
        }

        /**
         * @param code The path to the go code to build
         * 
         * @return builder
         * 
         */
        public Builder code(@Nullable String code) {
            $.code = code;
            return this;
        }

        public BuildGoPlainArgs build() {
            return $;
        }
    }

}
