// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.lambdabuilders.outputs;

import com.pulumi.asset.Archive;
import com.pulumi.core.annotations.CustomType;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class BuildGoResult {
    /**
     * @return The archive that contains the golang binary that will be deployed to the Lambda Function.
     * 
     */
    private @Nullable Archive asset;

    private BuildGoResult() {}
    /**
     * @return The archive that contains the golang binary that will be deployed to the Lambda Function.
     * 
     */
    public Optional<Archive> asset() {
        return Optional.ofNullable(this.asset);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(BuildGoResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable Archive asset;
        public Builder() {}
        public Builder(BuildGoResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.asset = defaults.asset;
        }

        @CustomType.Setter
        public Builder asset(@Nullable Archive asset) {

            this.asset = asset;
            return this;
        }
        public BuildGoResult build() {
            final var _resultValue = new BuildGoResult();
            _resultValue.asset = asset;
            return _resultValue;
        }
    }
}
