# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .build_go import *
from .provider import *
_utilities.register(
    resource_modules="""
[]
""",
    resource_packages="""
[
 {
  "pkg": "lambda-builders",
  "token": "pulumi:providers:lambda-builders",
  "fqn": "pulumi_lambda_builders",
  "class": "Provider"
 }
]
"""
)
