# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from . import _utilities

__all__ = [
    'BuildGoResult',
    'AwaitableBuildGoResult',
    'build_go',
    'build_go_output',
]

@pulumi.output_type
class BuildGoResult:
    def __init__(__self__, asset=None):
        if asset and not isinstance(asset, pulumi.Archive):
            raise TypeError("Expected argument 'asset' to be a pulumi.Archive")
        pulumi.set(__self__, "asset", asset)

    @property
    @pulumi.getter
    def asset(self) -> Optional[pulumi.Archive]:
        return pulumi.get(self, "asset")


class AwaitableBuildGoResult(BuildGoResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return BuildGoResult(
            asset=self.asset)


def build_go(architecture: Optional[str] = None,
             code: Optional[str] = None,
             opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableBuildGoResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['architecture'] = architecture
    __args__['code'] = code
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('lambda-builders:index:buildGo', __args__, opts=opts, typ=BuildGoResult).value

    return AwaitableBuildGoResult(
        asset=pulumi.get(__ret__, 'asset'))


@_utilities.lift_output_func(build_go)
def build_go_output(architecture: Optional[pulumi.Input[Optional[str]]] = None,
                    code: Optional[pulumi.Input[Optional[str]]] = None,
                    opts: Optional[pulumi.InvokeOptions] = None) -> pulumi.Output[BuildGoResult]:
    """
    Use this data source to access information about an existing resource.
    """
    ...
