// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function buildGo(args?: BuildGoArgs, opts?: pulumi.InvokeOptions): Promise<BuildGoResult> {
    args = args || {};

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("lambda-builders:index:buildGo", {
        "architecture": args.architecture,
        "code": args.code,
    }, opts);
}

export interface BuildGoArgs {
    architecture?: string;
    code?: string;
}

export interface BuildGoResult {
    readonly asset?: pulumi.asset.Archive;
}
export function buildGoOutput(args?: BuildGoOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<BuildGoResult> {
    return pulumi.output(args).apply((a: any) => buildGo(a, opts))
}

export interface BuildGoOutputArgs {
    architecture?: pulumi.Input<string>;
    code?: pulumi.Input<string>;
}
