// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export { BuildGoArgs, BuildGoResult, BuildGoOutputArgs } from "./buildGo";
export const buildGo: typeof import("./buildGo").buildGo = null as any;
export const buildGoOutput: typeof import("./buildGo").buildGoOutput = null as any;
utilities.lazyLoad(exports, ["buildGo","buildGoOutput"], () => require("./buildGo"));

export { ProviderArgs } from "./provider";
export type Provider = import("./provider").Provider;
export const Provider: typeof import("./provider").Provider = null as any;
utilities.lazyLoad(exports, ["Provider"], () => require("./provider"));

pulumi.runtime.registerResourcePackage("lambda-builders", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:lambda-builders") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
